Logsitic Regression 

logist regression is a machine learning classification algorithm that is used to predict the probability of a categorical dependent variable(y)

the dependent variable is a binary variable that contain data set as 1 (yes,success,etc) or 0 (no,failure,etc)



In [3]:
from sklearn.datasets import load_iris

In [4]:
iris=load_iris()
x=iris.data[50:]
y=iris.target[50:]

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=20,random_state=10)
from sklearn.linear_model import LogisticRegression

In [6]:
log=LogisticRegression()
log.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [7]:
log.coef_

array([[-1.48656639, -1.48739353,  2.19838534,  2.34496524]])

In [8]:
log.intercept_

array([-1.05756717])

In [9]:
import numpy as np

In [10]:
y1=log.coef_[0][0]*x_test[0][0] + log.coef_[0][1]*x_test[0][1] + log.coef_[0][2]*x_test[0][2] + log.coef_[0][3]*x_test[0][3] + log.intercept_

In [11]:
y1

array([-1.94765821])

In [12]:
t=x_test[0].reshape(1,-1)

In [18]:
t

array([[5.6, 2.5, 3.9, 1.1]])

In [19]:
x_test[0]

array([5.6, 2.5, 3.9, 1.1])

In [13]:
p=1/(1+np.exp(-y1))

In [17]:
p

array([0.12480893])

In [14]:
log.predict(t)

array([1])

In [15]:
log.score(x_test,y_test)

1.0

In [16]:
log.predict_proba(t)

array([[0.87519107, 0.12480893]])